canvas= document.getElementById("mycanvas");
ctx=canvas.getContext("2d");
Color="Blue"
ctx.beginPath();
ctx.strokeStyle=Color;
ctx.lineWidth=2;
ctx.arc(200,200,40,0,2*Math.PI);
ctx.stroke()
ctx.beginPath();
ctx.strokeStyle="Black";
ctx.lineWidth=2;
ctx.arc(250,200,40,0,2*Math.PI);
ctx.stroke()
ctx.beginPath();
ctx.strokeStyle="Red";
ctx.lineWidth=2;
ctx.arc(300,200,40,0,2*Math.PI);
ctx.stroke()
ctx.beginPath();
ctx.strokeStyle="Yellow";
ctx.lineWidth=2;
ctx.arc(225,250,40,0,2*Math.PI);
ctx.stroke()
ctx.beginPath();
ctx.strokeStyle="Green";
ctx.lineWidth=2;
ctx.arc(275,250,40,0,2*Math.PI);
ctx.stroke()
